### ISSUE TITLE
Auto import doesn't work in Pinia store

### ISSUE THREAD

**Issue by jimmiejackson414** [swisnl/nuxt-lucide-icons#11]
I'm trying to create an app-wide notification pinia store, but the auto-import doesn't appear to work in a .ts/.js file. I can verify that it does work correctly in a regular .vue file.

Here's an example of what I'm trying to do:

```typescript
import { defineStore } from 'pinia';
import { useToast } from '@/components/ui/toast';

type State = {
  loading: boolean;
};

type Getters = {
  //
};

type Actions = {
  notifyPositive: (description: string, title?: string) => void;
  notifyNegative: (description: string, title?: string) => void;
  notifyInfo: (description: string, title?: string) => void;
};

export const useAppStore = defineStore<'app', State, Getters, Actions>('app', {
  state () {
    return {
      loading: false,
    };
  },

  getters: {},

  actions: {
    notifyPositive (description, title) {
      const { toast } = useToast();
      toast({
        title,
        description,
        variant: 'positive',
        icon: IconCircleCheck, <-- error on this reference
      });
    },
    notifyNegative (description, title) {
      const { toast } = useToast();
      toast({
        title,
        description,
        variant: 'destructive',
        icon: IconCircleAlert, <-- error on this reference
      });
    },
    notifyInfo (description, title) {
      const { toast } = useToast();
      toast({
        title,
        description,
        variant: 'info',
        icon: IconInfo, <-- error on this reference
      });
    },
  },
});
```
Apologies if it's outside of the scope of this library, but i've never really come across this issue before. Do I actually need to manually import it in cases like this from somewhere?

**Comment by JaZo** [comment]
Hi Jimmie, auto-import only works in templates as far as I know. You should import it explicitly: https://nuxt.com/docs/guide/directory-structure/components#direct-imports

**Comment by jimmiejackson414** [comment]
I see. Tbh I'm not entirely sure of whether that's true or not (I'm able to have Pinia functions such as defineStore auto-imported into my Pinia store, for instance), but I was mainly trying to get away from explicitly importing from `lucide-vue-next` and so importing from `#components` still works fine for me in this case. I'll go ahead and close, thanks for the response!

**Comment by JaZo** [comment]
I meant auto-imports of components yes, other functions can indeed be auto-imported. But glad to hear you found a solution that works for you!
