### ISSUE TITLE
Lab icons

### ISSUE THREAD

**Issue by kueronya** [swisnl/nuxt-lucide-icons#12]
Hi there, appreciate your work. 
Any plans to support lab icons as well? 
https://github.com/lucide-icons/lucide-lab

**Comment by JaZo** [comment]
Unfortunately there are no plans to support the lab icons as well. They aren't really meant for direct usage in apps if I understand it correctly. And [the package](https://www.npmjs.com/package/@lucide/lab?activeTab=versions) doesn't get new versions either.

**Comment by kueronya** [comment]
> Unfortunately there are no plans to support the lab icons as well. They aren't really meant for direct usage in apps if I understand it correctly. And [the package](https://www.npmjs.com/package/@lucide/lab?activeTab=versions) doesn't get new versions either.

Alright, thx for your response.
