### ISSUE TITLE
I get 500  error loading dynamically imported module

### ISSUE THREAD

**Issue by XxHiroTTVxX** [swisnl/nuxt-lucide-icons#3]
```
500

error loading dynamically imported module: https://example.app.github.dev/_nuxt/pages/index.vue 
```

```
TypeError: error loading dynamically imported module: https://example.app.github.dev/_nuxt/pages/index.vue [vue-router.mjs:3471:20](https://example.app.github.dev/_nuxt/node_modules/.pnpm/vue-router@4.2.5_vue@3.3.8/node_modules/vue-router/dist/vue-router.mjs)
[nuxt] error caught during app initialization Error: error loading dynamically imported module: https://example.app.github.dev/_nuxt/pages/index.vue
Caused by: TypeError: error loading dynamically imported module: https://example.app.github.dev/_nuxt/pages/index.vue
```

**Comment by JaZo** [comment]
Can you add a minimal reproducible example (based on https://stackblitz.com/github/swisnl/nuxt-lucide-icons?file=playground%2Fapp.vue for example)? I can't look into this with just this info.

**Comment by XxHiroTTVxX** [comment]
mb for the late reply to this but to recreate my nuxt.config.ts looks like

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  pages: true,
  modules: [
    'nuxt-lucide-icons'
  ]
})
```

and the icons are in 

/pages/index.vue

but if I remove pages: true

and put the icons in app.vue in the project dir it will work with no error loading dynamically imported module

**Comment by XxHiroTTVxX** [comment]
and for some reason I js tried to recreate the page working by adding it to app.vue and removing pages and it returns a blank white page

**Comment by XxHiroTTVxX** [comment]
I might just be dumb tho but also when ```pnpm tauri dev``` is run it loads without any error in the app but localhost:3000 which is the dev server returns 500 error loading dynamically imported module

**Comment by XxHiroTTVxX** [comment]
> Can you add a minimal reproducible example (based on https://stackblitz.com/github/swisnl/nuxt-lucide-icons?file=playground%2Fapp.vue for example)? I can't look into this with just this info.

Also I wasn't able to recreate on there but I can provide the repo

**Comment by JaZo** [comment]
Sorry for the lack of response, I haven't had the time to look into this. If you can provide a minimal reproducible example by either a stackblitz or a minimal repo (not your entire project) I can more easily find out what's happening.

**Comment by XxHiroTTVxX** [comment]
yo so I figured out and its the stupidest thing ever but its because firefox 💀 it works perfectly fine on chrome is there something I can do to fix firefox to work lol

**Comment by XxHiroTTVxX** [comment]
oh mb for opening a dumb issue I figured out that UBlockOrigin was the issue for some reason

**Comment by XxHiroTTVxX** [comment]
**
![image](https://github.com/swisnl/nuxt-lucide-icons/assets/101534563/61e41db3-e3d5-4517-a1e9-058ec76ade58)
**

**Comment by JaZo** [comment]
Glad to see you figured it out! We banned adblockers during development for exactly this reason 😄

**Comment by StefanH-AT** [comment]
Just had the exact smae issue lol. Ublock origin just blocks anything called fingerprint.js or what? Maybe `lucide-vue-next` should rename that file?

**Comment by Aqu1tain** [comment]
> Just had the exact smae issue lol. Ublock origin just blocks anything called fingerprint.js or what? Maybe lucide-vue-next should rename that file?

I’m experiencing the same issue as reported here. uBlock Origin blocks the `fingerprint.js` file generated by `lucide-vue-next`, likely because the fingerprint icon name resembles a tracking-related term. This causes module loading failures in my Nuxt 3 application. Renaming the fingerprint icon itself seems challenging since it’s part of the Lucide icon set. 

Instead, could the lucide-vue-next team consider modifying the generated file naming convention (e.g., prefixing icon files or using a different pattern) to avoid triggering adblocker filters like EasyList? This would prevent similar issues with other icon names.

**Comment by JaZo** [comment]
> I’m experiencing the same issue as reported here. uBlock Origin blocks the `fingerprint.js` file generated by `lucide-vue-next`, likely because the fingerprint icon name resembles a tracking-related term. This causes module loading failures in my Nuxt 3 application. Renaming the fingerprint icon itself seems challenging since it’s part of the Lucide icon set.
> 
> Instead, could the lucide-vue-next team consider modifying the generated file naming convention (e.g., prefixing icon files or using a different pattern) to avoid triggering adblocker filters like EasyList? This would prevent similar issues with other icon names.

Maybe, but you should ask that [here](https://github.com/lucide-icons/lucide) as we don't maintain Lucide.

**Comment by rolfvandekrol** [comment]
@JaZo This seems fixed in the lucide library. https://github.com/lucide-icons/lucide/issues/2398 . Maybe the README should be updated accordingly?

**Comment by JaZo** [comment]
@rolfvandekrol thanks! https://github.com/swisnl/nuxt-lucide-icons/commit/5346d74d788e674279d5182480714c6531bc3fb4
